@startmindmap
* Безопасность данных
** Публичные данные
*** Данные и хранилище: объявления, маркетинговые материалы (client-mart-estate-db, client-mart-db, client-tour-db)
**** Утечка данных: Незначительный
***** Данные предназначены для публичного доступа, базовые меры защиты.
**** Потеря данных: Значительный
***** Потеря актуальных объявлений негативно влияет на клиентский опыт.
**** Искажение данных: Значительный
***** Неверная информация вводит клиента в заблуждение.
**** Некачественные данные: Значительный
***** Низкое качество данных снижает доверие к бренду.
**** Обесценивание данных: Значительный
***** Устаревшие или некорректные данные уменьшают их ценность.
** Внутренние данные
*** Данные и хранилище: внутренние логи, отчёты, операционные и аналитические данные (DWH Хранилище и прочие внутренние системы)
**** Утечка данных: Значительный
***** Утечка этих данных может раскрыть слабые места бизнес-процессов.
**** Потеря данных: Значительный
***** Потеря аналитических данных может остановить оперативное управление.
**** Искажение данных: Значительный
***** Неточные отчёты ведут к ошибкам в принятии решений.
**** Некачественные данные: Значительный
***** Системные сбои негативно влияют на аналитику.
**** Обесценивание данных: Значительный
***** Снижение качества данных ухудшает эффективность бизнес-процессов.
** Конфиденциальные данные
*** Данные и хранилище: персональные данные клиентов, CRM, транзакции, аутентификация (crm-db, crm-tenant-db, auth-db-1, tenant-core-db)
**** Утечка данных: Критический
***** Утечка персональных и транзакционных данных влечёт юридические санкции.
**** Потеря данных: Критический
***** Потеря данных приводит к сбоям в обслуживании клиентов.
**** Искажение данных: Критический
***** Изменённые данные могут повлиять на финансовые решения.
**** Некачественные данные: Критический
***** Низкое качество данных снижает эффективность аналитики.
**** Обесценивание данных: Критический
***** Снижение ценности данных ограничивает возможности развития.
** Секретные данные
*** Данные и хранилище: стратегические планы, интеграционные контракты, результаты аудитов, технические спецификации (закрытые системы, специализированные зашифрованные репозитории)
**** Утечка данных: Критический
***** Утечка стратегической информации наносит серьёзный ущерб.
**** Потеря данных: Критический
***** Потеря данных ставит под угрозу реализацию стратегических инициатив.
**** Искажение данных: Критический
***** Искажение данных ведёт к ошибочным управленческим решениям.
**** Некачественные данные: Критический
***** Некачественная информация снижает способность защищаться от угроз.
**** Обесценивание данных: Критический
***** Утрата актуальности снижает конкурентное преимущество.
@endmindmap
